print("------------------------------------------")
print("| FIAP paulista                          |")
print("| Análise e Desenvolvimento de Sistemas  |")
print("| Júlia Garcia Dellatorre                |")
print("| RM555767                               |")
print("| juhh1956@gmail.com                     |")
print("------------------------------------------")