nome = input("Digite um nome: ")
rm = input("Digite o rm: ")
email = input("Digite o email: ")

print("------------------------------------------")
print("| FIAP paulista")
print("| Análise e Desenvolvimento de Sistemas")
print("|", nome)
print("|", rm)
print("|", email)
print("------------------------------------------")